field: 19f2e599-5908-4b11-a440-48375ecb0914 # Bouwblokken
fieldLayouts:
  4f7d2d16-e923-482b-8fba-a4ccbc413d67:
    tabs:
      -
        elements:
          -
            fieldUid: 6ac97722-4ea7-439c-a61e-e886236abeed # Titel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 31a260de-9aed-4f28-9958-0ff7cb3f7eda # Tekst
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f7dca370-2621-4dd8-a0da-f221c72fc190 # Buttons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6793810c-0dd1-4bde-aade-39314406280d # Kleur
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6ac97722-4ea7-439c-a61e-e886236abeed: # Titel
    contentColumnType: text
    fieldGroup: null
    handle: fieldTitle
    instructions: ''
    name: Titel
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  31a260de-9aed-4f28-9958-0ff7cb3f7eda: # Tekst
    contentColumnType: text
    fieldGroup: null
    handle: fieldText
    instructions: ''
    name: Tekst
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  6793810c-0dd1-4bde-aade-39314406280d: # Kleur
    contentColumnType: text
    fieldGroup: null
    handle: fieldColor
    instructions: ''
    name: Kleur
    searchable: true
    settings:
      options:
        __assoc__:
          -
            - 4
            -
              __assoc__:
                -
                  - label
                  - white
                -
                  - color
                  - '#fff'
                -
                  - default
                  - '1'
          -
            - 0
            -
              __assoc__:
                -
                  - label
                  - black
                -
                  - color
                  - '#2B2828'
                -
                  - default
                  - ''
          -
            - 1
            -
              __assoc__:
                -
                  - label
                  - red
                -
                  - color
                  - '#FF004F'
                -
                  - default
                  - ''
          -
            - 2
            -
              __assoc__:
                -
                  - label
                  - blue
                -
                  - color
                  - '#2934FF'
                -
                  - default
                  - ''
          -
            - 3
            -
              __assoc__:
                -
                  - label
                  - yellow
                -
                  - color
                  - '#FDC119'
                -
                  - default
                  - ''
      palette: ''
      useConfigFile: ''
    translationKeyFormat: null
    translationMethod: none
    type: percipioglobal\colourswatches\fields\ColourSwatches
  f7dca370-2621-4dd8-a0da-f221c72fc190: # Buttons
    contentColumnType: string
    fieldGroup: null
    handle: fieldButtons
    instructions: ''
    name: Buttons
    searchable: true
    settings:
      columns:
        __assoc__:
          -
            - 4ca1fe7d-0d0d-4a9d-9f2d-fa2f92c7d852 # Button
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_3_fieldbuttons}}'
      fieldLayout: matrix
      maxRows: '2'
      minRows: ''
      placeholderKey: null
      propagationMethod: all
      selectionLabel: Button
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: default
name: Tekst
sortOrder: 2
