fieldLayouts:
  dc97b9f8-bbd7-4d21-be62-0e0051d85108:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: adde58c6-7061-4a76-a36c-e154ba0a679b # Achtergrond
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Inhoud
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 19f2e599-5908-4b11-a440-48375ecb0914 # Bouwblokken
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Blokken
        sortOrder: 2
handle: home
hasTitleField: false
name: Home
section: 0b8ef637-185b-43e0-9d2d-203186e37ee2
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
