fieldLayouts:
  8f70cbbe-76dc-455e-980f-cc02b70c1278:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: adde58c6-7061-4a76-a36c-e154ba0a679b # Achtergrond
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Inhoud
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 19f2e599-5908-4b11-a440-48375ecb0914 # Bouwblokken
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Blokken
        sortOrder: 2
handle: page
hasTitleField: true
name: 'Pagina''s'
section: 89dc02bd-1012-439d-84a9-da67f9a4a19e # Pagina
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
