contentColumnType: string
fieldGroup: 8f1c399b-481a-4dda-89ec-def2fcda6155
handle: fieldSocialMedia
instructions: ''
name: 'Sociale media'
searchable: false
settings:
  contentTable: '{{%matrixcontent_fieldsocialmedia}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
