contentColumnType: string
fieldGroup: 8f1c399b-481a-4dda-89ec-def2fcda6155
handle: fieldNav
instructions: ''
name: Navigatie
searchable: false
settings:
  contentTable: '{{%matrixcontent_fieldnav}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
